version: '3.8'

services:
  app:
    build: .
    container_name: baileys-api
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: baileys-api-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: baileys_api
    ports:
      - "3002:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
