onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - baileys
  - esbuild
  - prisma
  - protobufjs
  - sharp

patchedDependencies:
  baileys@7.0.0-rc.9: patches/baileys@7.0.0-rc.9.patch
